#!/usr/bin/env python3
"""Emit ontology/patterns.slop.yaml from sam-paech/antislop-sampler (Apache-2.0).

Sources (fetched at build time, cached in /tmp/opencode):
- slop_phrases_2025-04-07.json  -> top 300 over-used LLM phrases, one pattern each
- slop_regexes.txt              -> 3 generic anti-slop regexes, verbatim

The slop_words list is NOT imported: it is dominated by generated-story character
names (elara, rexus...) — fiction artifacts, noise for general-text detection.
The author's own README calls the list "not well optimised or curated".
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ontology" / "patterns.slop.yaml"
CACHE = Path("/tmp/opencode")
RAW = "https://raw.githubusercontent.com/sam-paech/antislop-sampler/main"
N_PHRASES = 300

FIX = "Known LLM overuse tell — cut or rewrite plainly."
SOURCE = "sam-paech/antislop-sampler"
LICENSE = "Apache-2.0"
PAPER = "paech-2510.15061"


def fetch(name: str) -> str:
    path = CACHE / name
    if not path.exists():
        path.write_text(urlopen(f"{RAW}/{name}", timeout=60).read().decode())
    return path.read_text()


def phrase_pattern(phrase: str) -> str:
    esc = re.escape(phrase)
    lb = r"\b" if phrase[0].isalnum() else ""
    rb = r"\b" if phrase[-1].isalnum() else ""
    return f"(?i){lb}{esc}{rb}"


def main() -> None:
    phrases = json.loads(fetch("slop_phrases_2025-04-07.json"))
    phrases.sort(key=lambda p: p[1], reverse=True)
    regexes = [l for l in fetch("slop_regexes.txt").splitlines() if l.strip()]

    rows: list[dict] = []
    seen_ids: set[str] = set()
    for phrase, count in phrases[:N_PHRASES]:
        pid = "slop_phrase_" + re.sub(r"[^a-z0-9]+", "_", phrase.lower()).strip("_")
        if pid in seen_ids:
            continue
        seen_ids.add(pid)
        rows.append(
            {
                "id": pid,
                "lane": "style",
                "unit": "span",
                "detector": "regex",
                "pattern": phrase_pattern(phrase),
                "fix": FIX,
                "source": SOURCE,
                "license": LICENSE,
                "min_len_words": 0,
                "paper": PAPER,
                "enabled": True,
            }
        )
    for regex, name in zip(regexes, ["not_x_but", "each_a", "every_a"]):
        rows.append(
            {
                "id": f"slop_{name}",
                "lane": "style",
                "unit": "span",
                "detector": "regex",
                "pattern": regex,
                "fix": FIX,
                "source": SOURCE,
                "license": LICENSE,
                "min_len_words": 0,
                "paper": PAPER,
                "enabled": True,
            }
        )

    lines = [
        "# SPDX-License-Identifier: Apache-2.0",
        "#",
        "# Generated by scripts/emit_slop_ontology.py — do not edit by hand.",
        "# Source: sam-paech/antislop-sampler (Apache-2.0), ICLR 2026 antislop paper (arXiv:2510.15061).",
        "# Phrases ranked by over-representation count in a large LLM-generated story dataset.",
        "#",
    ]
    for row in rows:
        lines.append(f"- id: {row['id']}")
        lines.append(f"  lane: {row['lane']}")
        lines.append(f"  unit: {row['unit']}")
        lines.append(f"  detector: {row['detector']}")
        lines.append(f"  pattern: {json.dumps(row['pattern'])}")
        lines.append(f"  fix: {json.dumps(row['fix'])}")
        lines.append(f"  source: {row['source']}")
        lines.append(f"  license: {row['license']}")
        lines.append(f"  min_len_words: {row['min_len_words']}")
        lines.append(f"  paper: {row['paper']}")
        lines.append(f"  enabled: true")
        lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", OUT, "|", len(rows), "patterns")


if __name__ == "__main__":
    main()
